### ISSUE TITLE
Jackson mapping Issue - Powertrack V2 

### ISSUE THREAD

**Issue by praveendevgit** [zauberlabs/gnip4j#52]
I'm getting the following error when try to parse v2 payload

`org.codehaus.jackson.map.JsonMappingException: Can not construct instance of com.zaubersoftware.gnip4j.api.model.Geometry, problem: abstract types can only be instantiated with additional type information
 at [Source: java.io.StringReader@26e35d06; line: 1, column: 1694] (through reference chain: com.zaubersoftware.gnip4j.api.model.Activity["location"]->com.zaubersoftware.gnip4j.api.model.Location["geo"]->com.zaubersoftware.gnip4j.api.model.Geo["coordinates"])
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.instantiationException(StdDeserializationContext.java:233)
	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:60)
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1863)
	at com.dev.search.gnip.TestVTwo.main(TestVTwo.java:29)
Exception in thread "main" java.lang.NullPointerException
	at com.dev.search.gnip.TestVTwo.main(TestVTwo.java:34)`

**Comment by jcodagnone** [comment]
TwetVTwo is using master? Can you log (near line 29) the payload you received?
