### ISSUE TITLE
Inflater has been closed

### ISSUE THREAD

**Issue by Hronom** [zauberlabs/gnip4j#68]
I receive next error while call `GnipStream.close()`
```
14:57:46 INFO [Thread-4] [DefaultGnipStream(info:84)] - Shutting Down prod
14:57:47 WARN [prod-consumer-http] [DefaultGnipStream(warn:114)] - Unexpected exception while consuming activity stream prod: Inflater has been closed
java.lang.NullPointerException: Inflater has been closed
	at java.util.zip.Inflater.ensureOpen(Inflater.java:389) ~[?:1.8.0_111]
	at java.util.zip.Inflater.inflate(Inflater.java:257) ~[?:1.8.0_111]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152) ~[?:1.8.0_111]
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) ~[?:1.8.0_111]
	at com.zaubersoftware.gnip4j.api.support.http.AbstractReleaseInputStream.read(AbstractReleaseInputStream.java:60) ~[gnip4j-core-2.2.0.jar:?]
	at com.zaubersoftware.gnip4j.api.stats.commonsio.ProxyInputStream.read(ProxyInputStream.java:79) ~[gnip4j-core-2.2.0.jar:?]
	at com.zaubersoftware.gnip4j.api.stats.commonsio.TeeInputStream.read(TeeInputStream.java:128) ~[gnip4j-core-2.2.0.jar:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_111]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_111]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_111]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_111]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_111]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_111]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_111]
	at com.zaubersoftware.gnip4j.api.impl.formats.ByLineFeedProcessor.process(ByLineFeedProcessor.java:51) ~[gnip4j-core-2.2.0.jar:?]
	at com.zaubersoftware.gnip4j.api.impl.DefaultGnipStream$GnipHttpConsumer.run(DefaultGnipStream.java:229) [gnip4j-core-2.2.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```
What is this?

I use:
```
        <!-- Gnip4j -->
        <dependency>
            <groupId>com.zaubersoftware.gnip4j</groupId>
            <artifactId>gnip4j-core</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.zaubersoftware.gnip4j</groupId>
            <artifactId>gnip4j-http</artifactId>
            <version>2.1.0</version>
        </dependency>
```

**Comment by Shikha1812** [comment]
I am getting the same issue

2018-05-15 17:32:26.497  INFO 36036 --- [pool-1-thread-3] c.z.gnip4j.api.impl.DefaultGnipStream    : Shutting Down dev
2018-05-15 17:32:26.504  WARN 36036 --- [v-consumer-http] c.z.gnip4j.api.impl.DefaultGnipStream    : Unexpected exception while consuming activity stream dev: Inflater has been closed

java.lang.NullPointerException: Inflater has been closed
	at java.util.zip.Inflater.ensureOpen(Inflater.java:389) ~[na:1.8.0_141]
	at java.util.zip.Inflater.inflate(Inflater.java:257) ~[na:1.8.0_141]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152) ~[na:1.8.0_141]
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) ~[na:1.8.0_141]
	at com.zaubersoftware.gnip4j.api.support.http.AbstractReleaseInputStream.read(AbstractReleaseInputStream.java:60) ~[gnip4j-core-2.1.0.jar:na]
	at com.zaubersoftware.gnip4j.api.stats.commonsio.ProxyInputStream.read(ProxyInputStream.java:79) ~[gnip4j-core-2.1.0.jar:na]
	at com.zaubersoftware.gnip4j.api.stats.commonsio.TeeInputStream.read(TeeInputStream.java:128) ~[gnip4j-core-2.1.0.jar:na]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_141]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_141]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_141]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_141]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[na:1.8.0_141]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[na:1.8.0_141]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[na:1.8.0_141]
	at com.zaubersoftware.gnip4j.api.impl.formats.ByLineFeedProcessor.process(ByLineFeedProcessor.java:51) ~[gnip4j-core-2.1.0.jar:na]
	at com.zaubersoftware.gnip4j.api.impl.DefaultGnipStream$GnipHttpConsumer.run(DefaultGnipStream.java:229) ~[gnip4j-core-2.1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]

-- Shutting down
